server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    # Redirigir peticiones JSP al backend interno
    location ~ \.jsp$ {
        proxy_pass http://backend-service.inventario-itu.svc.cluster.local:8080;
    }
}
