apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: inventario-itu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: wildfly
        image: fuanis-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
