version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend-service:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend-service:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend-service

volumes:
  mongo_data:
