apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-web
  template:
    metadata:
      labels:
        app: inventario-web
    spec:
      containers:
      - name: inventario-web
        image: fuanis-inventario:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: inventario-web
