apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-frontend
  namespace: inventario-itu
  labels:
    app: inventario-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-frontend
  template:
    metadata:
      labels:
        app: inventario-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: fuanis-inventario-frontend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http-frontend