apiVersion: v1
kind: Service
metadata:
  name: inventario-frontend
  namespace: inventario-itu
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # Puerto de acceso externo en Minikube/Clúster
    protocol: TCP
  selector:
    app: inventario-frontend